#!/usr/bin/env python
"""Generate (or verify) the student and instructor notebooks from notebooks/workshop_source.py.

    python notebooks/build_notebooks.py           # write both .ipynb files
    python notebooks/build_notebooks.py --check   # exit 1 if either file is out of date (used in CI)
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import nbformat

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "workshop_source.py"
STUDENT = HERE / "workshop_student.ipynb"
INSTRUCTOR = HERE / "workshop_instructor.ipynb"


def load_cells():
    spec = importlib.util.spec_from_file_location("workshop_source", SOURCE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.CELLS


def build(cells, variant: str) -> nbformat.NotebookNode:
    nb = nbformat.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
        "colab": {"provenance": [], "toc_visible": True},
        "workshop": {"variant": variant, "generated_by": "notebooks/build_notebooks.py"},
    }
    out = []
    n_ex = 0
    for i, c in enumerate(cells):
        cid = f"{variant[:3]}-{i:03d}"
        if c["type"] == "markdown":
            cell = nbformat.v4.new_markdown_cell(c["source"], id=cid)
        elif c["type"] == "note":
            if variant != "instructor":
                continue
            cell = nbformat.v4.new_markdown_cell("> 🎤 " + c["source"].replace("\n", "\n> "), id=cid)
            cell.metadata["instructor_note"] = True
        elif c["type"] == "code":
            cell = nbformat.v4.new_code_cell(c["source"], id=cid)
        elif c["type"] == "exercise":
            n_ex += 1
            cell = nbformat.v4.new_code_cell(c["instructor"] if variant == "instructor" else c["student"], id=cid)
            cell.metadata["exercise"] = c["key"]
        else:
            raise ValueError(c["type"])
        out.append(cell)
    nb.cells = out
    if variant == "instructor":
        nb.cells.insert(0, nbformat.v4.new_markdown_cell(
            "# 🎓 INSTRUCTOR VERSION: all exercises completed, presenter notes inline\n"
            "Generated from `notebooks/workshop_source.py`; do not edit this file directly.", id="ins-head"))
    return nb


def render(nb) -> str:
    return nbformat.writes(nb) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    cells = load_cells()
    targets = {STUDENT: build(cells, "student"), INSTRUCTOR: build(cells, "instructor")}
    stale = []
    for path, nb in targets.items():
        text = render(nb)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path.name}: {len(nb.cells)} cells "
                  f"({sum(1 for c in nb.cells if c.metadata.get('exercise'))} exercise cells)")
    if args.check:
        if stale:
            print("OUT OF DATE:", ", ".join(stale), "- run python notebooks/build_notebooks.py")
            return 1
        print("notebooks are in sync with workshop_source.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
